// AUTO-GENERATED by scripts/generate-events.mjs — do not edit manually
// Last generated: 2026-03-04T21:50:13.427Z

export interface ArchiveEvent {
  id: string
  type: "corporate" | "nightlife" | "weddings"
  title: string
  venue: string | null
  city: string | null
  tags: string[]
  featured: boolean
  cover: string | null
  motion: string[]
  templateImages: string[]
  rawImages: string[]
  totalImageCount: number
}

export const EVENTS: ArchiveEvent[] = [
  {
    "id": "activepear-fashionshow",
    "type": "corporate",
    "title": "Active Pear Fashion Show",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/activepear-fashionshow/front/0080-active_pear_fashion_show_-d1-template.jpg",
    "motion": [],
    "templateImages": [
      "/events/activepear-fashionshow/template/0054-active_pear_fashion_show_-d1-template.jpg",
      "/events/activepear-fashionshow/template/0056-active_pear_fashion_show_-d1-template.jpg",
      "/events/activepear-fashionshow/template/0058-active_pear_fashion_show_-d1-template.jpg",
      "/events/activepear-fashionshow/template/0065-active_pear_fashion_show_-d1-template.jpg",
      "/events/activepear-fashionshow/template/0067-active_pear_fashion_show_-d1-template.jpg",
      "/events/activepear-fashionshow/template/0078-active_pear_fashion_show_-d1-template.jpg",
      "/events/activepear-fashionshow/template/0080-active_pear_fashion_show_-d1-template.jpg",
      "/events/activepear-fashionshow/template/0092-active_pear_fashion_show_-d1-template.jpg",
      "/events/activepear-fashionshow/template/0096-active_pear_fashion_show_-d1-template.jpg",
      "/events/activepear-fashionshow/template/0139-active_pear_fashion_show_-d1-template.jpg"
    ],
    "rawImages": [
      "/events/activepear-fashionshow/raw/0059-active_pear_fashion_show_-d1.jpg",
      "/events/activepear-fashionshow/raw/0075-active_pear_fashion_show_-d1.jpg",
      "/events/activepear-fashionshow/raw/0095-active_pear_fashion_show_-d1.jpg"
    ],
    "totalImageCount": 13
  },
  {
    "id": "devour-prevail-book1",
    "type": "nightlife",
    "title": "Devour & Prevail: Album Release",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/devour-prevail-book1/front/0037-Devour__Prevail_Book_1__Album_Release_Party-d1-template.jpg",
    "motion": [
      "/events/devour-prevail-book1/gif/0046-Devour__Prevail_Book_1__Album_Release_Party-d1.mp4"
    ],
    "templateImages": [
      "/events/devour-prevail-book1/template/0003-Devour__Prevail_Book_1__Album_Release_Party-d1-template.jpg",
      "/events/devour-prevail-book1/template/0006-Devour__Prevail_Book_1__Album_Release_Party-d1-template.jpg",
      "/events/devour-prevail-book1/template/0009-Devour__Prevail_Book_1__Album_Release_Party-d1-template.jpg",
      "/events/devour-prevail-book1/template/0013-Devour__Prevail_Book_1__Album_Release_Party-d1-template.jpg",
      "/events/devour-prevail-book1/template/0027-Devour__Prevail_Book_1__Album_Release_Party-d1-template.jpg",
      "/events/devour-prevail-book1/template/0030-Devour__Prevail_Book_1__Album_Release_Party-d1-template.jpg",
      "/events/devour-prevail-book1/template/0037-Devour__Prevail_Book_1__Album_Release_Party-d1-template.jpg",
      "/events/devour-prevail-book1/template/0038-Devour__Prevail_Book_1__Album_Release_Party-d1-template.jpg",
      "/events/devour-prevail-book1/template/0047-Devour__Prevail_Book_1__Album_Release_Party-d1-template.jpg"
    ],
    "rawImages": [],
    "totalImageCount": 9
  },
  {
    "id": "dropoutside-la",
    "type": "nightlife",
    "title": "Drop Outside LA",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/dropoutside-la/front/0014-dropoutsidela_-d1.mp4",
    "motion": [
      "/events/dropoutside-la/gif/0014-dropoutsidela_-d1.mp4",
      "/events/dropoutside-la/gif/0026-dropoutsidela_-d1.mp4"
    ],
    "templateImages": [
      "/events/dropoutside-la/template/0021-dropoutsidela_-d1-template.jpg",
      "/events/dropoutside-la/template/0022-dropoutsidela_-d1-template.jpg",
      "/events/dropoutside-la/template/0036-dropoutsidela_-d1-template.jpg",
      "/events/dropoutside-la/template/0044-dropoutsidela_-d1-template.jpg",
      "/events/dropoutside-la/template/0045-dropoutsidela_-d1-template.jpg"
    ],
    "rawImages": [
      "/events/dropoutside-la/raw/0035-dropoutsidela_-d1.jpg",
      "/events/dropoutside-la/raw/0066-dropoutsidela_-d1.jpg"
    ],
    "totalImageCount": 7
  },
  {
    "id": "dsrpt-noiselab-episode3",
    "type": "nightlife",
    "title": "DSRPT Noize Lab III",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/dsrpt-noiselab-episode3/front/0166-NOIZE_LAB-d1-template.jpg",
    "motion": [
      "/events/dsrpt-noiselab-episode3/gif/0019-NOIZE_LAB-d1.mp4",
      "/events/dsrpt-noiselab-episode3/gif/0030-NOIZE_LAB-d1.mp4",
      "/events/dsrpt-noiselab-episode3/gif/0052-NOIZE_LAB-d1.mp4",
      "/events/dsrpt-noiselab-episode3/gif/0062-NOIZE_LAB-d1.mp4",
      "/events/dsrpt-noiselab-episode3/gif/0150-NOIZE_LAB-d1.mp4",
      "/events/dsrpt-noiselab-episode3/gif/0190-NOIZE_LAB-d1.mp4",
      "/events/dsrpt-noiselab-episode3/gif/0194-NOIZE_LAB-d1.mp4"
    ],
    "templateImages": [
      "/events/dsrpt-noiselab-episode3/template/0021-NOIZE_LAB-d1-template.jpg",
      "/events/dsrpt-noiselab-episode3/template/0026-NOIZE_LAB-d1-template.jpg",
      "/events/dsrpt-noiselab-episode3/template/0063-NOIZE_LAB-d1-template.jpg",
      "/events/dsrpt-noiselab-episode3/template/0069-NOIZE_LAB-d1-template.jpg",
      "/events/dsrpt-noiselab-episode3/template/0101-NOIZE_LAB-d1-template.jpg",
      "/events/dsrpt-noiselab-episode3/template/0103-NOIZE_LAB-d1-template.jpg",
      "/events/dsrpt-noiselab-episode3/template/0111-NOIZE_LAB-d1-template.jpg",
      "/events/dsrpt-noiselab-episode3/template/0130-NOIZE_LAB-d1-template.jpg",
      "/events/dsrpt-noiselab-episode3/template/0137-NOIZE_LAB-d1-template.jpg",
      "/events/dsrpt-noiselab-episode3/template/0149-NOIZE_LAB-d1-template.jpg",
      "/events/dsrpt-noiselab-episode3/template/0165-NOIZE_LAB-d1-template.jpg",
      "/events/dsrpt-noiselab-episode3/template/0166-NOIZE_LAB-d1-template (1).jpg"
    ],
    "rawImages": [],
    "totalImageCount": 12
  },
  {
    "id": "dsrpt-noiselab-episode4",
    "type": "nightlife",
    "title": "DSRPT Noize Lab IV",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/dsrpt-noiselab-episode4/front/0100-NOIZE_LAB_004-d1-template.jpg",
    "motion": [
      "/events/dsrpt-noiselab-episode4/gif/0133-NOIZE_LAB_004-d1 (1).mp4",
      "/events/dsrpt-noiselab-episode4/gif/0247-NOIZE_LAB_004-d1.mp4",
      "/events/dsrpt-noiselab-episode4/gif/0323-NOIZE_LAB_004-d1.mp4",
      "/events/dsrpt-noiselab-episode4/gif/0354-NOIZE_LAB_004-d1.mp4",
      "/events/dsrpt-noiselab-episode4/gif/0355-NOIZE_LAB_004-d1.mp4",
      "/events/dsrpt-noiselab-episode4/gif/0391-NOIZE_LAB_004-d1.mp4",
      "/events/dsrpt-noiselab-episode4/gif/0397-NOIZE_LAB_004-d1.mp4",
      "/events/dsrpt-noiselab-episode4/gif/0484-NOIZE_LAB_004-d1.mp4",
      "/events/dsrpt-noiselab-episode4/gif/0488-NOIZE_LAB_004-d1 (1).mp4",
      "/events/dsrpt-noiselab-episode4/gif/0534-NOIZE_LAB_004-d1.mp4",
      "/events/dsrpt-noiselab-episode4/gif/0547-NOIZE_LAB_004-d1.mp4",
      "/events/dsrpt-noiselab-episode4/gif/0576-NOIZE_LAB_004-d1.mp4"
    ],
    "templateImages": [
      "/events/dsrpt-noiselab-episode4/template/0091-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0100-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0102-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0119-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0126-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0130-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0137-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0151-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0155-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0166-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0218-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0220-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0230-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0239-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0249-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0273-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0275-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0284-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0352-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0360-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0362-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0409-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0457-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0467-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0483-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0491-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0529-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0539-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0548-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0599-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0637-NOIZE_LAB_004-d1-template.jpg",
      "/events/dsrpt-noiselab-episode4/template/0679-NOIZE_LAB_004-d1-template.jpg"
    ],
    "rawImages": [],
    "totalImageCount": 32
  },
  {
    "id": "dsrpt-ericbellinger-cover-releaseparty",
    "type": "nightlife",
    "title": "DSRPT: Eric Bellinger Release",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/dsrpt-ericbellinger-cover-releaseparty/front/0035-Eric_-_ep006-d1-template.jpg",
    "motion": [
      "/events/dsrpt-ericbellinger-cover-releaseparty/gif/0015-Eric_-_ep006-d1.mp4",
      "/events/dsrpt-ericbellinger-cover-releaseparty/gif/0020-Eric_-_ep006-d1.mp4",
      "/events/dsrpt-ericbellinger-cover-releaseparty/gif/0043-Eric_-_ep006-d1.mp4",
      "/events/dsrpt-ericbellinger-cover-releaseparty/gif/0064-Eric_-_ep006-d1 (1).mp4",
      "/events/dsrpt-ericbellinger-cover-releaseparty/gif/0077-Eric_-_ep006-d1.mp4",
      "/events/dsrpt-ericbellinger-cover-releaseparty/gif/0198-Eric_-_ep006-d1.mp4",
      "/events/dsrpt-ericbellinger-cover-releaseparty/gif/0361-Eric_-_ep006-d1.mp4",
      "/events/dsrpt-ericbellinger-cover-releaseparty/gif/0417-Eric_-_ep006-d1.mp4",
      "/events/dsrpt-ericbellinger-cover-releaseparty/gif/0451-Eric_-_ep006-d1.mp4"
    ],
    "templateImages": [
      "/events/dsrpt-ericbellinger-cover-releaseparty/template/0035-Eric_-_ep006-d1-template.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/template/0066-Eric_-_ep006-d1-template.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/template/0094-Eric_-_ep006-d1-template.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/template/0135-Eric_-_ep006-d1-template.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/template/0153-Eric_-_ep006-d1-template.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/template/0171-Eric_-_ep006-d1-template.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/template/0195-Eric_-_ep006-d1-template.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/template/0207-Eric_-_ep006-d1-template.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/template/0234-Eric_-_ep006-d1-template.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/template/0360-Eric_-_ep006-d1-template.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/template/0467-Eric_-_ep006-d1-template.jpg"
    ],
    "rawImages": [
      "/events/dsrpt-ericbellinger-cover-releaseparty/raw/0063-Eric_-_ep006-d1.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/raw/0081-Eric_-_ep006-d1.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/raw/0086-Eric_-_ep006-d1.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/raw/0121-Eric_-_ep006-d1.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/raw/0217-Eric_-_ep006-d1.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/raw/0358-Eric_-_ep006-d1.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/raw/0359-Eric_-_ep006-d1.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/raw/0428-Eric_-_ep006-d1.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/raw/0444-Eric_-_ep006-d1.jpg",
      "/events/dsrpt-ericbellinger-cover-releaseparty/raw/0468-Eric_-_ep006-d1.jpg"
    ],
    "totalImageCount": 21
  },
  {
    "id": "dsrpt-mdot-birthday",
    "type": "nightlife",
    "title": "DSRPT: M.Dot Celebration",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/dsrpt-mdot-birthday/template/0043-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
    "motion": [
      "/events/dsrpt-mdot-birthday/gif/0038-HAPPY_BIRTHDAY_M_DOT-d1.mp4",
      "/events/dsrpt-mdot-birthday/gif/0102-HAPPY_BIRTHDAY_M_DOT-d1.mp4",
      "/events/dsrpt-mdot-birthday/gif/0227-HAPPY_BIRTHDAY_M_DOT-d1.mp4",
      "/events/dsrpt-mdot-birthday/gif/0286-HAPPY_BIRTHDAY_M_DOT-d1.mp4",
      "/events/dsrpt-mdot-birthday/gif/0302-HAPPY_BIRTHDAY_M_DOT-d1.mp4",
      "/events/dsrpt-mdot-birthday/gif/0316-HAPPY_BIRTHDAY_M_DOT-d1.mp4",
      "/events/dsrpt-mdot-birthday/gif/0355-HAPPY_BIRTHDAY_M_DOT-d1.mp4"
    ],
    "templateImages": [
      "/events/dsrpt-mdot-birthday/template/0043-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0055-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0065-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0074-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0103-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0119-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0152-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0170-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0192-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0222-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0235-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0255-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0276-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0279-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0309-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0341-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0346-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg",
      "/events/dsrpt-mdot-birthday/template/0349-HAPPY_BIRTHDAY_M_DOT-d1-template.jpg"
    ],
    "rawImages": [
      "/events/dsrpt-mdot-birthday/raw/0066-HAPPY_BIRTHDAY_M_DOT-d1.jpg",
      "/events/dsrpt-mdot-birthday/raw/0180-HAPPY_BIRTHDAY_M_DOT-d1.jpg",
      "/events/dsrpt-mdot-birthday/raw/0208-HAPPY_BIRTHDAY_M_DOT-d1.jpg",
      "/events/dsrpt-mdot-birthday/raw/0210-HAPPY_BIRTHDAY_M_DOT-d1.jpg",
      "/events/dsrpt-mdot-birthday/raw/0281-HAPPY_BIRTHDAY_M_DOT-d1.jpg",
      "/events/dsrpt-mdot-birthday/raw/0310-HAPPY_BIRTHDAY_M_DOT-d1.jpg",
      "/events/dsrpt-mdot-birthday/raw/0351-HAPPY_BIRTHDAY_M_DOT-d1.jpg"
    ],
    "totalImageCount": 25
  },
  {
    "id": "easports-battleflied6-friendsandfamily",
    "type": "corporate",
    "title": "EA Sports: Battlefield 6",
    "venue": "Ripple Studios",
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/easports-battleflied6-friendsandfamily/front/0165-ripple_studios-d1-template.jpg",
    "motion": [
      "/events/easports-battleflied6-friendsandfamily/gif/0126-ripple_studios-d1.mp4"
    ],
    "templateImages": [
      "/events/easports-battleflied6-friendsandfamily/template/0041-ripple_studios-d1-template.jpg",
      "/events/easports-battleflied6-friendsandfamily/template/0069-ripple_studios-d1-template.jpg",
      "/events/easports-battleflied6-friendsandfamily/template/0165-ripple_studios-d1-template.jpg",
      "/events/easports-battleflied6-friendsandfamily/template/0215-ripple_studios-d1-template.jpg"
    ],
    "rawImages": [
      "/events/easports-battleflied6-friendsandfamily/raw/0028-ripple_studios-d1.jpg",
      "/events/easports-battleflied6-friendsandfamily/raw/0038-ripple_studios-d1.jpg",
      "/events/easports-battleflied6-friendsandfamily/raw/0137-ripple_studios-d1.jpg",
      "/events/easports-battleflied6-friendsandfamily/raw/0156-ripple_studios-d1.jpg",
      "/events/easports-battleflied6-friendsandfamily/raw/0229-ripple_studios-d1.jpg",
      "/events/easports-battleflied6-friendsandfamily/raw/0252-ripple_studios-d1.jpg",
      "/events/easports-battleflied6-friendsandfamily/raw/0333-ripple_studios-d1.jpg",
      "/events/easports-battleflied6-friendsandfamily/raw/0419-ripple_studios-d1.jpg"
    ],
    "totalImageCount": 12
  },
  {
    "id": "enjoyment-worldwide-sofihotel",
    "type": "nightlife",
    "title": "Enjoyment Worldwide",
    "venue": "Sofitel Los Angeles",
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/enjoyment-worldwide-sofihotel/front/0057-Enjoyment_Worldwide-d1-template.jpg",
    "motion": [
      "/events/enjoyment-worldwide-sofihotel/gif/0051-Enjoyment_Worldwide-d1.mp4",
      "/events/enjoyment-worldwide-sofihotel/gif/0056-Enjoyment_Worldwide-d1.mp4",
      "/events/enjoyment-worldwide-sofihotel/gif/0101-Enjoyment_Worldwide-d1.mp4",
      "/events/enjoyment-worldwide-sofihotel/gif/0300-Enjoyment_Worldwide-d1.mp4"
    ],
    "templateImages": [
      "/events/enjoyment-worldwide-sofihotel/template/0032-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0053-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0057-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0068-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0081-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0095-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0104-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0128-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0154-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0174-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0220-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0224-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0234-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0243-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0264-Enjoyment_Worldwide-d1-template.jpg",
      "/events/enjoyment-worldwide-sofihotel/template/0289-Enjoyment_Worldwide-d1-template.jpg"
    ],
    "rawImages": [
      "/events/enjoyment-worldwide-sofihotel/raw/0078-Enjoyment_Worldwide-d1.jpg",
      "/events/enjoyment-worldwide-sofihotel/raw/0097-Enjoyment_Worldwide-d1.jpg",
      "/events/enjoyment-worldwide-sofihotel/raw/0109-Enjoyment_Worldwide-d1.jpg",
      "/events/enjoyment-worldwide-sofihotel/raw/0141-Enjoyment_Worldwide-d1.jpg",
      "/events/enjoyment-worldwide-sofihotel/raw/0205-Enjoyment_Worldwide-d1.jpg"
    ],
    "totalImageCount": 21
  },
  {
    "id": "flair-runclub-eqinox-v1",
    "type": "corporate",
    "title": "Equinox Run Club I",
    "venue": "Equinox",
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/flair-runclub-eqinox-v1/front/0022-EQUINOX_RUN_CLUB-d1-template (1).jpg",
    "motion": [
      "/events/flair-runclub-eqinox-v1/gif/0016-EQUINOX_RUN_CLUB-d1.mp4",
      "/events/flair-runclub-eqinox-v1/gif/0026-EQUINOX_RUN_CLUB-d1 (1).mp4"
    ],
    "templateImages": [
      "/events/flair-runclub-eqinox-v1/template/0018-EQUINOX_RUN_CLUB-d1-template.jpg",
      "/events/flair-runclub-eqinox-v1/template/0022-EQUINOX_RUN_CLUB-d1-template (1).jpg",
      "/events/flair-runclub-eqinox-v1/template/0030-EQUINOX_RUN_CLUB-d1-template.jpg",
      "/events/flair-runclub-eqinox-v1/template/0045-EQUINOX_RUN_CLUB-d1-template.jpg",
      "/events/flair-runclub-eqinox-v1/template/0058-EQUINOX_RUN_CLUB-d1-template.jpg",
      "/events/flair-runclub-eqinox-v1/template/0062-EQUINOX_RUN_CLUB-d1-template.jpg",
      "/events/flair-runclub-eqinox-v1/template/0071-EQUINOX_RUN_CLUB-d1-template.jpg",
      "/events/flair-runclub-eqinox-v1/template/0076-EQUINOX_RUN_CLUB-d1-template.jpg",
      "/events/flair-runclub-eqinox-v1/template/0081-EQUINOX_RUN_CLUB-d1-template.jpg",
      "/events/flair-runclub-eqinox-v1/template/0100-EQUINOX_RUN_CLUB-d1-template.jpg",
      "/events/flair-runclub-eqinox-v1/template/0110-EQUINOX_RUN_CLUB-d1-template.jpg",
      "/events/flair-runclub-eqinox-v1/template/0120-EQUINOX_RUN_CLUB-d1-template.jpg",
      "/events/flair-runclub-eqinox-v1/template/0130-EQUINOX_RUN_CLUB-d1-template.jpg"
    ],
    "rawImages": [
      "/events/flair-runclub-eqinox-v1/raw/0024-EQUINOX_RUN_CLUB-d1.jpg",
      "/events/flair-runclub-eqinox-v1/raw/0074-EQUINOX_RUN_CLUB-d1.jpg",
      "/events/flair-runclub-eqinox-v1/raw/0096-EQUINOX_RUN_CLUB-d1.jpg",
      "/events/flair-runclub-eqinox-v1/raw/0102-EQUINOX_RUN_CLUB-d1.jpg",
      "/events/flair-runclub-eqinox-v1/raw/0105-EQUINOX_RUN_CLUB-d1.jpg",
      "/events/flair-runclub-eqinox-v1/raw/0112-EQUINOX_RUN_CLUB-d1.jpg",
      "/events/flair-runclub-eqinox-v1/raw/0127-EQUINOX_RUN_CLUB-d1.jpg"
    ],
    "totalImageCount": 20
  },
  {
    "id": "flair-runclub-eqinox-v2",
    "type": "corporate",
    "title": "Equinox Run Club II",
    "venue": "Equinox",
    "city": null,
    "tags": [],
    "featured": true,
    "cover": "/events/flair-runclub-eqinox-v2/front/0101-FLAIR_-d1.mp4",
    "motion": [
      "/events/flair-runclub-eqinox-v2/gif/0010-FLAIR_-d1.mp4",
      "/events/flair-runclub-eqinox-v2/gif/0068-FLAIR_-d1.mp4",
      "/events/flair-runclub-eqinox-v2/gif/0094-FLAIR_-d1.mp4",
      "/events/flair-runclub-eqinox-v2/gif/0101-FLAIR_-d1.mp4",
      "/events/flair-runclub-eqinox-v2/gif/0102-FLAIR_-d1.mp4",
      "/events/flair-runclub-eqinox-v2/gif/0105-FLAIR_-d1.mp4",
      "/events/flair-runclub-eqinox-v2/gif/0106-FLAIR_-d1.mp4"
    ],
    "templateImages": [
      "/events/flair-runclub-eqinox-v2/template/0017-FLAIR_-d1-template.jpg",
      "/events/flair-runclub-eqinox-v2/template/0020-FLAIR_-d1-template.jpg",
      "/events/flair-runclub-eqinox-v2/template/0040-FLAIR_-d1-template.jpg",
      "/events/flair-runclub-eqinox-v2/template/0046-FLAIR_-d1-template.jpg",
      "/events/flair-runclub-eqinox-v2/template/0079-FLAIR_-d1-template.jpg",
      "/events/flair-runclub-eqinox-v2/template/0093-FLAIR_-d1-template.jpg"
    ],
    "rawImages": [
      "/events/flair-runclub-eqinox-v2/raw/0021-FLAIR_-d1.jpg",
      "/events/flair-runclub-eqinox-v2/raw/0026-FLAIR_-d1.jpg"
    ],
    "totalImageCount": 8
  },
  {
    "id": "wedding-jasmineandadrian-cityla",
    "type": "weddings",
    "title": "Jasmine & Adrian",
    "venue": "City Club LA",
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/wedding-jasmineandadrian-cityla/front/0370-wedding_-d1-template.jpg",
    "motion": [
      "/events/wedding-jasmineandadrian-cityla/gif/0144-wedding_-d1.mp4",
      "/events/wedding-jasmineandadrian-cityla/gif/0380-wedding_-d1.mp4",
      "/events/wedding-jasmineandadrian-cityla/gif/0384-wedding_-d1.mp4",
      "/events/wedding-jasmineandadrian-cityla/gif/0399-wedding_-d1.mp4"
    ],
    "templateImages": [
      "/events/wedding-jasmineandadrian-cityla/template/0037-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0043-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0049-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0060-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0067-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0086-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0093-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0101-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0106-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0115-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0129-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0153-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0193-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0200-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0232-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0246-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0250-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0260-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0270-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0308-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0319-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0325-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0340-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0359-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0367-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0370-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0381-wedding_-d1-template.jpg",
      "/events/wedding-jasmineandadrian-cityla/template/0400-wedding_-d1-template.jpg"
    ],
    "rawImages": [],
    "totalImageCount": 28
  },
  {
    "id": "la-maison-olivera",
    "type": "nightlife",
    "title": "La Maison Olivera",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": true,
    "cover": "/events/la-maison-olivera/front/0013-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
    "motion": [
      "/events/la-maison-olivera/gif/0004-Gabe_Oliveiras_25th_birthday-d1.mp4",
      "/events/la-maison-olivera/gif/0027-Gabe_Oliveiras_25th_birthday-d1 (1).mp4",
      "/events/la-maison-olivera/gif/0049-Gabe_Oliveiras_25th_birthday-d1 (1).mp4",
      "/events/la-maison-olivera/gif/0081-Gabe_Oliveiras_25th_birthday-d1 (1).mp4",
      "/events/la-maison-olivera/gif/0104-Gabe_Oliveiras_25th_birthday-d1 (1).mp4",
      "/events/la-maison-olivera/gif/0115-Gabe_Oliveiras_25th_birthday-d1.mp4",
      "/events/la-maison-olivera/gif/0129-Gabe_Oliveiras_25th_birthday-d1 (1).mp4",
      "/events/la-maison-olivera/gif/0147-Gabe_Oliveiras_25th_birthday-d1.mp4",
      "/events/la-maison-olivera/gif/0172-Gabe_Oliveiras_25th_birthday-d1 (1).mp4",
      "/events/la-maison-olivera/gif/0178-Gabe_Oliveiras_25th_birthday-d1.mp4",
      "/events/la-maison-olivera/gif/0227-Gabe_Oliveiras_25th_birthday-d1.mp4",
      "/events/la-maison-olivera/gif/0268-Gabe_Oliveiras_25th_birthday-d1.mp4",
      "/events/la-maison-olivera/gif/0294-Gabe_Oliveiras_25th_birthday-d1.mp4"
    ],
    "templateImages": [
      "/events/la-maison-olivera/template/0023-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0033-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0050-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0052-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0055-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0067-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0071-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0095-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0118-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0136-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0148-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0156-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0157-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0184-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0187-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0193-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0212-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0260-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0272-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0285-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0298-Gabe_Oliveiras_25th_birthday-d1-template.jpg",
      "/events/la-maison-olivera/template/0307-Gabe_Oliveiras_25th_birthday-d1-template.jpg"
    ],
    "rawImages": [],
    "totalImageCount": 22
  },
  {
    "id": "jstaparty-newyears",
    "type": "nightlife",
    "title": "New Year's Eve",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": true,
    "cover": "/events/jstaparty-newyears/front/0045-nye-d1-template (1).jpg",
    "motion": [
      "/events/jstaparty-newyears/gif/0003-nye-d1.mp4",
      "/events/jstaparty-newyears/gif/0042-nye-d1.mp4",
      "/events/jstaparty-newyears/gif/0173-nye-d1.mp4",
      "/events/jstaparty-newyears/gif/0217-nye-d1.mp4",
      "/events/jstaparty-newyears/gif/0475-nye-d1.mp4",
      "/events/jstaparty-newyears/gif/0502-nye-d1.mp4"
    ],
    "templateImages": [
      "/events/jstaparty-newyears/template/0018-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0027-nye-d1-template (1).jpg",
      "/events/jstaparty-newyears/template/0037-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0045-nye-d1-template (1).jpg",
      "/events/jstaparty-newyears/template/0061-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0076-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0081-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0105-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0136-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0145-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0166-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0179-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0220-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0226-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0247-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0286-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0343-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0352-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0376-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0439-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0472-nye-d1-template.jpg",
      "/events/jstaparty-newyears/template/0474-nye-d1-template.jpg"
    ],
    "rawImages": [
      "/events/jstaparty-newyears/raw/0025-nye-d1.jpg",
      "/events/jstaparty-newyears/raw/0135-nye-d1.jpg",
      "/events/jstaparty-newyears/raw/0214-nye-d1.jpg",
      "/events/jstaparty-newyears/raw/0229-nye-d1.jpg",
      "/events/jstaparty-newyears/raw/0255-nye-d1.jpg",
      "/events/jstaparty-newyears/raw/0275-nye-d1.jpg",
      "/events/jstaparty-newyears/raw/0282-nye-d1.jpg",
      "/events/jstaparty-newyears/raw/0296-nye-d1.jpg",
      "/events/jstaparty-newyears/raw/0310-nye-d1.jpg",
      "/events/jstaparty-newyears/raw/0359-nye-d1.jpg",
      "/events/jstaparty-newyears/raw/0373-nye-d1.jpg",
      "/events/jstaparty-newyears/raw/0478-nye-d1.jpg",
      "/events/jstaparty-newyears/raw/0506-nye-d1.jpg"
    ],
    "totalImageCount": 35
  },
  {
    "id": "posion-mansionparty",
    "type": "nightlife",
    "title": "Poison Mansion",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/posion-mansionparty/front/0025-poison_-d1.mp4",
    "motion": [
      "/events/posion-mansionparty/gif/0025-poison_-d1.mp4",
      "/events/posion-mansionparty/gif/0100-poison_-d1.mp4",
      "/events/posion-mansionparty/gif/0126-poison_-d1.mp4",
      "/events/posion-mansionparty/gif/0175-poison_-d1.mp4"
    ],
    "templateImages": [
      "/events/posion-mansionparty/template/0023-poison_-d1-template.jpg",
      "/events/posion-mansionparty/template/0034-poison_-d1-template.jpg",
      "/events/posion-mansionparty/template/0037-poison_-d1-template.jpg",
      "/events/posion-mansionparty/template/0040-poison_-d1-template.jpg",
      "/events/posion-mansionparty/template/0043-poison_-d1-template.jpg",
      "/events/posion-mansionparty/template/0105-poison_-d1-template.jpg",
      "/events/posion-mansionparty/template/0112-poison_-d1-template.jpg",
      "/events/posion-mansionparty/template/0127-poison_-d1-template.jpg",
      "/events/posion-mansionparty/template/0146-poison_-d1-template.jpg",
      "/events/posion-mansionparty/template/0193-poison_-d1-template.jpg",
      "/events/posion-mansionparty/template/0222-poison_-d1-template.jpg"
    ],
    "rawImages": [
      "/events/posion-mansionparty/raw/0016-poison_-d1.jpg",
      "/events/posion-mansionparty/raw/0018-poison_-d1.jpg",
      "/events/posion-mansionparty/raw/0042-poison_-d1.jpg",
      "/events/posion-mansionparty/raw/0097-poison_-d1.jpg",
      "/events/posion-mansionparty/raw/0139-poison_-d1.jpg",
      "/events/posion-mansionparty/raw/0149-poison_-d1.jpg",
      "/events/posion-mansionparty/raw/0177-poison_-d1.jpg"
    ],
    "totalImageCount": 18
  },
  {
    "id": "slowhrs-cozychoas-photoshoot-party",
    "type": "nightlife",
    "title": "Slow Hours: Cozy Chaos",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/slowhrs-cozychoas-photoshoot-party/front/0033-COZY_CHAOS-d1-template.jpg",
    "motion": [
      "/events/slowhrs-cozychoas-photoshoot-party/gif/0009-COZY_CHAOS-d1.mp4",
      "/events/slowhrs-cozychoas-photoshoot-party/gif/0017-COZY_CHAOS-d1.mp4",
      "/events/slowhrs-cozychoas-photoshoot-party/gif/0035-COZY_CHAOS-d1.mp4",
      "/events/slowhrs-cozychoas-photoshoot-party/gif/0086-COZY_CHAOS-d1.mp4",
      "/events/slowhrs-cozychoas-photoshoot-party/gif/0159-COZY_CHAOS-d1.mp4",
      "/events/slowhrs-cozychoas-photoshoot-party/gif/0161-COZY_CHAOS-d1.mp4",
      "/events/slowhrs-cozychoas-photoshoot-party/gif/0169-COZY_CHAOS-d1.mp4",
      "/events/slowhrs-cozychoas-photoshoot-party/gif/0205-COZY_CHAOS-d1.mp4"
    ],
    "templateImages": [
      "/events/slowhrs-cozychoas-photoshoot-party/template/0013-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0022-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0033-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0039-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0046-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0052-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0065-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0091-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0093-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0102-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0175-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0185-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0193-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0202-COZY_CHAOS-d1-template.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/template/0209-COZY_CHAOS-d1-template.jpg"
    ],
    "rawImages": [
      "/events/slowhrs-cozychoas-photoshoot-party/raw/0003-COZY_CHAOS-d1.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/raw/0021-COZY_CHAOS-d1.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/raw/0045-COZY_CHAOS-d1.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/raw/0089-COZY_CHAOS-d1.jpg",
      "/events/slowhrs-cozychoas-photoshoot-party/raw/0165-COZY_CHAOS-d1.jpg"
    ],
    "totalImageCount": 20
  },
  {
    "id": "spice-dayrave",
    "type": "nightlife",
    "title": "Spice Day Rave",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/spice-dayrave/front/0063-Spice_-d1-template.jpg",
    "motion": [
      "/events/spice-dayrave/gif/0015-Spice_-d1.mp4",
      "/events/spice-dayrave/gif/0057-Spice_-d1.mp4",
      "/events/spice-dayrave/gif/0099-Spice_-d1.mp4",
      "/events/spice-dayrave/gif/0150-Spice_-d1.mp4",
      "/events/spice-dayrave/gif/0213-Spice_-d1.mp4",
      "/events/spice-dayrave/gif/0228-Spice_-d1.mp4",
      "/events/spice-dayrave/gif/0248-Spice_-d1.mp4",
      "/events/spice-dayrave/gif/0275-Spice_-d1.mp4"
    ],
    "templateImages": [
      "/events/spice-dayrave/template/0017-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0046-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0060-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0063-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0073-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0092-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0125-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0139-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0160-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0182-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0192-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0196-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0198-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0204-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0230-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0241-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0276-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0278-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0306-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0320-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0338-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0384-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0389-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0391-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0406-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0417-Spice_-d1-template.jpg",
      "/events/spice-dayrave/template/0423-Spice_-d1-template.jpg"
    ],
    "rawImages": [
      "/events/spice-dayrave/raw/0022-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0067-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0106-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0133-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0141-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0157-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0194-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0211-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0242-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0266-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0329-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0347-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0351-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0378-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0396-Spice_-d1.jpg",
      "/events/spice-dayrave/raw/0422-Spice_-d1.jpg"
    ],
    "totalImageCount": 43
  },
  {
    "id": "wya",
    "type": "nightlife",
    "title": "WYA Night",
    "venue": null,
    "city": null,
    "tags": [],
    "featured": false,
    "cover": "/events/wya/front/0451-WYA-d1-template.jpg",
    "motion": [
      "/events/wya/gif/0066-WYA-d1.mp4",
      "/events/wya/gif/0161-WYA-d1.mp4"
    ],
    "templateImages": [
      "/events/wya/template/0045-WYA-d1-template.jpg",
      "/events/wya/template/0065-WYA-d1-template.jpg",
      "/events/wya/template/0070-WYA-d1-template.jpg",
      "/events/wya/template/0090-WYA-d1-template.jpg",
      "/events/wya/template/0116-WYA-d1-template.jpg",
      "/events/wya/template/0144-WYA-d1-template.jpg",
      "/events/wya/template/0151-WYA-d1-template.jpg",
      "/events/wya/template/0282-WYA-d1-template.jpg",
      "/events/wya/template/0289-WYA-d1-template.jpg",
      "/events/wya/template/0323-WYA-d1-template.jpg",
      "/events/wya/template/0344-WYA-d1-template.jpg",
      "/events/wya/template/0443-WYA-d1-template.jpg",
      "/events/wya/template/0451-WYA-d1-template.jpg",
      "/events/wya/template/0486-WYA-d1-template.jpg",
      "/events/wya/template/0532-WYA-d1-template.jpg"
    ],
    "rawImages": [
      "/events/wya/raw/0006-WYA-d1.jpg",
      "/events/wya/raw/0016-WYA-d1.jpg",
      "/events/wya/raw/0029-WYA-d1.jpg",
      "/events/wya/raw/0051-WYA-d1.jpg",
      "/events/wya/raw/0052-WYA-d1.jpg",
      "/events/wya/raw/0109-WYA-d1.jpg",
      "/events/wya/raw/0133-WYA-d1.jpg",
      "/events/wya/raw/0159-WYA-d1.jpg",
      "/events/wya/raw/0171-WYA-d1.jpg",
      "/events/wya/raw/0201-WYA-d1.jpg",
      "/events/wya/raw/0212-WYA-d1.jpg",
      "/events/wya/raw/0231-WYA-d1.jpg",
      "/events/wya/raw/0343-WYA-d1.jpg",
      "/events/wya/raw/0506-WYA-d1.jpg",
      "/events/wya/raw/0521-WYA-d1.jpg",
      "/events/wya/raw/0534-WYA-d1.jpg"
    ],
    "totalImageCount": 31
  }
] as const

export function getEventBySlug(slug: string): ArchiveEvent | undefined {
  return EVENTS.find((e) => e.id === slug)
}

export function getEventsByType(type: ArchiveEvent["type"]): ArchiveEvent[] {
  return EVENTS.filter((e) => e.type === type)
}

export function getFeaturedEvents(): ArchiveEvent[] {
  return EVENTS.filter((e) => e.featured)
}
